# Generated by Django 5.1.4 on 2024-12-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_of_accounts', models.IntegerField()),
            ],
        ),
    ]
